config/routes.rb
Rails.application.routes.draw do

    namespace :browser, path: '/', constraints: lambda {|request| request.subdomain.present? && request.subdomain != 'www'} do
        get '/' => 'item_browser#land', :as => :landing
        get '/search' => 'item_browser#search', :as => :search
        get '/item/:id' => 'item_browser#show_item', :as => :item
        get '/category/:id' => 'item_browser#browse_category', :as => :category
    end

    namespace :homepage, path: '/' do
        get '/' => 'landing#land', :as => :landing
        get 'signup' => 'signup#signup', :as => :signup
        post 'signup' => 'signup#do_signup'
        get 'billing' => 'signup#billing', :as => :billing
        post 'billing' => 'signup#do_billing'
        get 'signin' => 'signin#show', :as => :signin
        post 'signin' => 'signin#signin'
        get 'signout' => 'signin#signout', :as => :signout
        get 'reset' => 'signin#reset_form', :as => :reset_password_form
        post 'reset' => 'signin#send_reset_email'
        get 'reset_password/:token' => 'signin#reset_password', :as => :reset_password
        post'reset_password/:token' => 'signin#update_password'
    end

    namespace :inventory do 
        get '/account' => 'account#show', :as => :account
        patch '/account' => 'account#update_user'
        get '/' => 'landing#land', :as => :landing
        resources :items do 
            resources :item_photos do
                member do 
                    get 'primary' => 'item_photos#set_primary', :as => :set_primary
                end
            end
        end
        resources :item_categories do 
            resources :item_sub_categories
        end
        scope 'settings' do 
            get 'application' => 'settings#application_settings', :as => :application_settings
            post 'application' => 'settings#update_application_settings'
            get 'apperance' => 'settings#apperance_settings', :as => :apperance_settings
            patch 'apperance' => 'settings#update_apperance_settings'
            get 'remove_logo' => 'settings#remove_logo', :as => :remove_logo 

            scope :billing do 
                get '/' => 'billing#view', :as => :billing
                get 'add_card' => 'billing#new_card', :as => :new_card
                post 'add_card' => 'billing#create_card'
                get 'primary_card' => 'billing#make_primary', :as => :make_primary_card
                get 'delete_card' => 'billing#delete_card', :as => :delete_card
                get 'cancel' => 'billing#confirm_cancel_account', :as => :cancel_account
                post 'cancel' => 'billing#cancel_account'
            end
        end
    end

    namespace :help do 
        get '/' => 'articles#landing', :as => :landing
        get ':article' => 'articles#article', :as => :article
    end
end

app/controllers/homepage/homepage_controller.rb
class Homepage::HomepageController < ApplicationController 
    layout 'homepage'
    force_ssl if Rails.env.production?

    def current_instance 
       @current_instance ||= current_user.try(:instance)
    end
    helper_method :current_instance

    def current_user
        @current_user ||= User.find(session[:user_id]) if session[:user_id]
    end
    helper_method :current_user


    def logged_in? 
        session[:user_id].present?
    end
    helper_method :logged_in?

end

app/controllers/homepage/landing_controller.rb
class Homepage::LandingController < Homepage::HomepageController
  def land
  end
end

app/controllers/homepage/signin_controller.rb
class Homepage::SigninController < Homepage::HomepageController
    layout 'homepage_full' 

    def show
        return redirect_to inventory_landing_path if logged_in?
    end

    def signin
        user = User.joins(:email).find_by(emails: { address: params[:email] })
        if user && user.try(:authenticate, params[:password])
            session[:user_id] = user.id
            redirect_to inventory_landing_path
        else
            @error = "Email address or password not valid."
            render 'show' 
        end
    end

    def signout
        session[:user_id] = nil
        redirect_to homepage_signin_path
    end

    def reset_form
    end

    def send_reset_email
        @user = User.joins(:email).find_by(emails: { address: params[:email]})
        if @user 
            @user.update(password_recovery_token: SecureRandom.hex(10))
            UserMailer.reset_password(@user).deliver
            render 'reset_email_sent'
        else
            @error = "Email address not found."
            render 'reset_form' 
        end
    end

    def reset_password
        @user = User.find_by_password_recovery_token(params[:token])
        unless @user 
            @error = "The reset link you used was invalid or has expired. Enter your email address below to reset your password."
            render 'reset_form'
        end
    end

    def update_password
        @user = User.find_by_password_recovery_token(params[:token])
        return render 'reset_form' unless @user
        @user.password = params[:password]
        @user.password_confirmation = params[:password_confirmation]
        @user.password_recovery_token = nil
        if @user.save
            session[:user_id] = @user.id
            redirect_to inventory_landing_path
        else
            render 'reset_password'
        end
    end

end

app/controllers/homepage/signup_controller.rb
class Homepage::SignupController < Homepage::HomepageController
    layout 'homepage_full'
    if Rails.env.production? 
        force_ssl
    end

    def signup
        build_instance
        build_user
    end

    def do_signup
        @instance = Instance.new(signup_params)
        @user = User.new(user_params)
        @user.instance = @instance
        @instance.valid?
        @user.valid?
        if @instance.valid? && @user.valid?
            @instance.save
            @user.save
            session[:user_id] = @user.id
            redirect_to homepage_billing_path
        else
            render 'signup'
        end
    end

    def billing

    end

    def do_billing
        current_instance.customer.cards.create(:card => params[:stripe_token])
        current_instance.customer.subscriptions.create(:plan => 'basic')
        complete_signup
        redirect_to inventory_landing_path
    end

    def complete
    end


    private 

    def complete_signup
        UserMailer.welcome(current_user).deliver
        sns_message = " Company: #{current_instance.company.company_name}\nInstance name: #{current_instance.instance_name}"
        AWS::SNS.new.topics['arn:aws:sns:us-east-1:357993104421:hockd_system'].publish sns_message, subject: 'New Signup'
        current_instance.landing_triggers.create(view_name: 'getting_started')
    end

    def build_instance
        @instance ||= Instance.new
        @instance.build_company unless @instance.company
        @instance.company.build_location unless @instance.company.location
        @instance.company.build_phone_number unless @instance.company.phone_number
    end

    def build_user 
        @user ||= User.new
        @user.build_phone_number unless @user.phone_number
        @user.build_location unless @user.location
        @user.build_email unless @user.email
    end

    def signup_params 
        permitted =  params.require(:instance).permit(
            :instance_name, 
            :company_attributes => [
                :company_name,
                location_attributes: [:street_address, :city, :state, :postal_code],
                phone_number_attributes: [:number]
        ]
        )
    end
    def user_params
        params.require(:user).permit(
            :first_name, 
            :last_name, 
            :password, :password_confirmation,
            email_attributes: [ :address ],
            phone_number_attributes: [ :number ],
            location_attributes: [:street_address, :city, :state, :postal_code],
        )
    end


end

app/helpers/homepage/landing_helper.rb
module Homepage::LandingHelper
end

app/helpers/homepage/signin_helper.rb
module Homepage::SigninHelper
end

app/helpers/homepage/signup_helper.rb
module Homepage::SignupHelper
end

app/views/homepage/signup/billing.html.erb
<div class="billing-form">
    <div class="logo"><%= link_to 'hockd', homepage_landing_path %> </div>
    <div class="full-page-form">
        <h3>Plan Details</h3>
        <div class="details">
            <div class="label">Plan name</div> <div class="value">hockd basic</div>
        </div>
        <div class="details">
            <div class="label">Monthly subscription </div> <div class="value">$59.00</div>
        </div>
        <p>Your subscription includes full use of the service. Your account will be charged a subscription fee of <strong>$59.00</strong> per month.
        <hr/>
        <h3>Billing Details</h3>
        <div class="stripe-error"></div>
        <%= form_tag homepage_billing_path, id: 'card-form' do %>
            <%= hidden_field_tag :stripe_token %>
            <div class="input">
                <label>Card number</label> <input type="text" id="card-number"/>
            </div>
            <div class="card-exp-cvc">
                <div class="input">
                    <label>Exp Month</label>
                    <%= select_month Time.current, {use_month_numbers: true, use_two_digit_numbers: true}, id: 'card-exp-month' %>
                </div>
                <div class="input">
                    <label>Exp Year</label>
                    <%= select_year Time.current, {start_year: Time.current.year}, id: 'card-exp-year' %>
                </div>
                <div class="input">
                    <label>CVC Code</label>
                    <input type="text" id="card-cvc"/>
                </div>
            </div>
            <div class="hint">
                The CVC code is your card's security code. Generally this is the three digit code on the back of the card.
            </div>
            <div class="form-actions">
                <button type="submit" class="new-card-button">Finish Signup</button>
            </div>
        <% end %>
    </div>
</div>

app/views/homepage/signup/complete.html.erb
<h1>Homepage::Signup#complete</h1>
<p>Find me in app/views/homepage/signup/complete.html.erb</p>

app/views/homepage/signup/signup.html.erb
<div class="signup-form">
    <div class="logo"><%= link_to 'hockd', homepage_landing_path %></div>
    <div class="form full-page-form">
        <h3>Account Signup</h3>
        <%= simple_form_for @instance, url: homepage_signup_path do |instance_form| %>
            <%= simple_fields_for @user do |user_form| %>
                <fieldset>
                    <legend>User information</legend>
                    <div class="name">
                        <%= user_form.input :first_name %>
                        <%= user_form.input :last_name %>
                    </div>
                    <%= user_form.fields_for :phone_number do |phone_number_form| %>
                        <%= phone_number_form.input :number, label: 'Phone number', hint: 'This phone number will not be shared and will only be used if we need to contact you.' %>
                    <% end %>
                    <%= user_form.fields_for :email do |email_form| %>
                        <%= email_form.input :address, label: 'Email address', hint: 'This email address will only be used to send you notifications about your account, retrieve your password, and login. It will never be shared.' %>
                    <% end %>
                    <div class="password">
                        <%= user_form.input :password, hint: 'Passwords should be greater than 5 characters' %>
                        <%= user_form.input :password_confirmation , hint: 'Retype password to confirm.' %>
                    </div>
                </fieldset>
            <% end %>
            <fieldset>
                <legend>Company information</legend>
                <%= instance_form.fields_for :company do |company_form| %>
                    <%= company_form.input :company_name %>
                    <%= company_form.fields_for :phone_number do |phone_number_form| %>
                        <%= phone_number_form.input :number, label: 'Phone Number' %>
                    <% end %>
                    <%= company_form.fields_for :location do |location_form| %>
                        <%= location_form.input :street_address %>
                        <div class="city-state-zip">
                            <%= location_form.input :city %>
                            <%= location_form.input :state, collection: us_states %>
                            <%= location_form.input :postal_code %>
                        </div>
                    <% end %>
                <% end %>
            </fieldset>
            <fieldset>
                <legend>Application information</legend>
                <%= instance_form.input :instance_name, label: 'Application name', hint: 'The application name is a unique name that identifies your application. This name should be a short name that reflects your business. Your custom url will be generated using this name. For instance if your company\'s is Pawn Palace, your application name could be pawnpalace. This would make your application accessible by customers at <strong>http://pawnpalace.hockd.com</strong>. <strong>NOTE: This value may not contain spaces or special characters.</strong>'.html_safe %>
            </fieldset>
            <div class="form-actions">
                <%= instance_form.submit 'Continue' %>
            </div>
        <% end %>
    </div>
</div>