config/routes.rb
Rails.application.routes.draw do

    namespace :browser, path: '/', constraints: lambda {|request| request.subdomain.present? && request.subdomain != 'www'} do
        get '/' => 'item_browser#land', :as => :landing
        get '/search' => 'item_browser#search', :as => :search
        get '/item/:id' => 'item_browser#show_item', :as => :item
        get '/category/:id' => 'item_browser#browse_category', :as => :category
    end

    namespace :homepage, path: '/' do
        get '/' => 'landing#land', :as => :landing
        get 'signup' => 'signup#signup', :as => :signup
        post 'signup' => 'signup#do_signup'
        get 'billing' => 'signup#billing', :as => :billing
        post 'billing' => 'signup#do_billing'
        get 'signin' => 'signin#show', :as => :signin
        post 'signin' => 'signin#signin'
        get 'signout' => 'signin#signout', :as => :signout
        get 'reset' => 'signin#reset_form', :as => :reset_password_form
        post 'reset' => 'signin#send_reset_email'
        get 'reset_password/:token' => 'signin#reset_password', :as => :reset_password
        post'reset_password/:token' => 'signin#update_password'
    end

    namespace :inventory do 
        get '/account' => 'account#show', :as => :account
        patch '/account' => 'account#update_user'
        get '/' => 'landing#land', :as => :landing
        resources :items do 
            resources :item_photos do
                member do 
                    get 'primary' => 'item_photos#set_primary', :as => :set_primary
                end
            end
        end
        resources :item_categories do 
            resources :item_sub_categories
        end
        scope 'settings' do 
            get 'application' => 'settings#application_settings', :as => :application_settings
            post 'application' => 'settings#update_application_settings'
            get 'apperance' => 'settings#apperance_settings', :as => :apperance_settings
            patch 'apperance' => 'settings#update_apperance_settings'
            get 'remove_logo' => 'settings#remove_logo', :as => :remove_logo 

            scope :billing do 
                get '/' => 'billing#view', :as => :billing
                get 'add_card' => 'billing#new_card', :as => :new_card
                post 'add_card' => 'billing#create_card'
                get 'primary_card' => 'billing#make_primary', :as => :make_primary_card
                get 'delete_card' => 'billing#delete_card', :as => :delete_card
                get 'cancel' => 'billing#confirm_cancel_account', :as => :cancel_account
                post 'cancel' => 'billing#cancel_account'
            end
        end
    end

    namespace :help do 
        get '/' => 'articles#landing', :as => :landing
        get ':article' => 'articles#article', :as => :article
    end
end

app/controllers/browser/browser_controller.rb
class Browser::BrowserController < ApplicationController 
    layout :get_layout

    before_action :theme_view_path 

    private

    def current_instance
        @instance ||= Instance.find_by_instance_name(request.subdomain)
    end
    helper_method :current_instance

    def current_theme
        @theme ||= current_instance.apperance_setting.theme_name
    end
    helper_method :current_theme

    def get_layout
        "browser/#{current_theme}"
    end

    def theme_view_path
        prepend_view_path "app/views/themes/#{current_theme}"
    end

end

app/controllers/browser/item_browser_controller.rb
class Browser::ItemBrowserController < Browser::BrowserController
    

    def land
        return render 'no_items' if current_instance.items.count == 0
        @items = current_instance.items.search(params[:q]).result.page(page).per(per)
        @hero_item = current_instance.items.order('featured desc, view_count desc').limit(1).first
        @featured_items = current_instance.items.order('featured desc, view_count desc').limit(24).offset(1)
        @featured_items = @featured_items.limit(@featured_items.count - ( @featured_items.count % 4)) if @featured_items.count < 24 && @featured_items.count > 4
    end


    def search
        @items = handle_filters(current_instance.items).search(params[:q]).result.page(page).per(per)
        @sub_categories = ItemSubCategory.where(id: current_instance.items.search(params[:q]).result.select(:item_sub_category_id)) 
        @title = "Searching for \"#{params[:q]['title_cont']}\"" if params[:q]
        render 'show_items'
    end


    def show_item
        @item = current_instance.items.find(params[:id])
        @item.update(last_viewed_at: Time.current, view_count: @item.view_count+1)
    end



    def browse_category 
       @category = current_instance.item_categories.find(params[:id])
       @items = handle_filters @category.items
       @sub_categories = @category.item_sub_categories
       @display = params[:d] || 'grid'
       @title = "Browseing #{@category}"
       render 'show_items'
    end

    private


    def handle_filters(items)
       items = items.where(item_sub_category_id: params[:sc]) if params[:sc].present?
       items = items.where('price < ?', params[:price]) if params[:price].present?
       items = items.order(params[:sort]) if params[:sort]
       items = items.page(page).per(per)
       return items
    end

    def sub_category
        return nil unless params[:sc]
        @category.item_sub_categories.find(params[:sc])    
    end

    def page
        params[:page] || 0
    end

    def per 
        params[:per] || 20
    end
    




end

app/helpers/browser/browser_helper.rb
module Browser::BrowserHelper
    def browser_page_title 
        "#{current_instance.company.company_name} - #{number_to_phone current_instance.company.phone_number.number} - #{current_instance.company.location.address}"
    end
end

app/helpers/browser/item_browser_helper.rb
module Browser::ItemBrowserHelper


    def featured_item(item)
        render partial: 'browser/featured_item', object: item 
    end


    def item_display_style
        params[:d] || 'list'
    end

    def display_style_link (icon, display_value) 
        active_class = (item_display_style == display_value ? 'active' : nil)
        link_to icon(icon), url_for(params.merge(d: display_value)), class: active_class
    end

    def filter_link(param, text, value=nil) 
        merge_params = {}
        merge_params[param] = value
        if value 
            content_tag :li, class: (params[param] == value.to_s ? 'active' : nil) do 
                link_to text, url_for(params.merge(merge_params))
            end
        else
            active_class = 'active' if params[param].nil?
            content_tag :li, class: active_class do 
                link_to 'All', url_for(params.merge(merge_params))
            end 
        end
    end

end

app/views/browser/_categories.html.erb
<div class="categories">
    <h3>Categories</h3>
    <div class="categories-inner">
        <div class="wrapper">
            <% current_instance.item_categories.each do |item_category| %>
                <div class="category">
                    <h4><%= item_category.name %></h4>
                    <ul>
                        <% item_category.item_sub_categories.each do |sub_category| %>
                            <li><%= link_to sub_category.name, browser_category_path(item_category, sc: sub_category.id) %></li>
                        <% end %>
                    </ul>
                </div>
            <% end %>
        </div>
    </div>
</div>

app/views/browser/_featured_item.html.erb
<div class="featured-item">
    <%= link_to [:browser, featured_item]  do %>
        <div class="image">
            <%= image_tag featured_item.primary_photo_url(:small), size: featured_item.primary_photo_size(:small) %>
        </div>
        <div class="details">
            <div class="title"><%= truncate(featured_item.title) %></div>
            <div class="description"><%= truncate(featured_item.description, length: 200) %></div>
            <div class="price"><%= number_to_currency featured_item.price %></div>
        </div>
    <% end %>
</div>

app/views/browser/_nav.html.erb
<div class="navigation">
    <div class="navigation-wrapper">
        <% if current_instance.items.count > 0 %>
            <div class="nav">
                <div class="menu">
                    <ul>
                        <% current_instance.item_categories.popular.limit(8).each do |category| %>
                            <li><%= link_to category, browser_category_path(category) %></li>
                        <% end %>
                    </ul>
                </div>
                <div class="search">
                    <%= render 'browser/search' %>
                </div>
            </div>
        <% end %>
    </div>
</div>

app/views/browser/_search.html.erb
<div class="slide-search">
        <%= search_form_for @item_search || Item.search, url: browser_search_path do |f| %>
            <button type="button"><%= icon 'search' %></button>
            <div class="search-container">
                <%=  f.search_field :title_cont, placeholder: 'Find an item...' %>
            </div>
        <% end %>
</div>