config/routes.rb
Rails.application.routes.draw do

    namespace :browser, path: '/', constraints: lambda {|request| request.subdomain.present? && request.subdomain != 'www'} do
        get '/' => 'item_browser#land', :as => :landing
        get '/search' => 'item_browser#search', :as => :search
        get '/item/:id' => 'item_browser#show_item', :as => :item
        get '/category/:id' => 'item_browser#browse_category', :as => :category
    end

    namespace :homepage, path: '/' do
        get '/' => 'landing#land', :as => :landing
        get 'signup' => 'signup#signup', :as => :signup
        post 'signup' => 'signup#do_signup'
        get 'billing' => 'signup#billing', :as => :billing
        post 'billing' => 'signup#do_billing'
        get 'signin' => 'signin#show', :as => :signin
        post 'signin' => 'signin#signin'
        get 'signout' => 'signin#signout', :as => :signout
        get 'reset' => 'signin#reset_form', :as => :reset_password_form
        post 'reset' => 'signin#send_reset_email'
        get 'reset_password/:token' => 'signin#reset_password', :as => :reset_password
        post'reset_password/:token' => 'signin#update_password'
    end

    namespace :inventory do 
        get '/account' => 'account#show', :as => :account
        patch '/account' => 'account#update_user'
        get '/' => 'landing#land', :as => :landing
        resources :items do 
            resources :item_photos do
                member do 
                    get 'primary' => 'item_photos#set_primary', :as => :set_primary
                end
            end
        end
        resources :item_categories do 
            resources :item_sub_categories
        end
        scope 'settings' do 
            get 'application' => 'settings#application_settings', :as => :application_settings
            post 'application' => 'settings#update_application_settings'
            get 'apperance' => 'settings#apperance_settings', :as => :apperance_settings
            patch 'apperance' => 'settings#update_apperance_settings'
            get 'remove_logo' => 'settings#remove_logo', :as => :remove_logo 

            scope :billing do 
                get '/' => 'billing#view', :as => :billing
                get 'add_card' => 'billing#new_card', :as => :new_card
                post 'add_card' => 'billing#create_card'
                get 'primary_card' => 'billing#make_primary', :as => :make_primary_card
                get 'delete_card' => 'billing#delete_card', :as => :delete_card
                get 'cancel' => 'billing#confirm_cancel_account', :as => :cancel_account
                post 'cancel' => 'billing#cancel_account'
            end
        end
    end

    namespace :help do 
        get '/' => 'articles#landing', :as => :landing
        get ':article' => 'articles#article', :as => :article
    end
end

app/models/item.rb
class Item < ActiveRecord::Base
    has_many :photos, class_name: 'ItemPhoto'
    belongs_to :item_category
    belongs_to :item_sub_category
    belongs_to :instance
    validates :title, presence: {message: 'Please enter a title for this item.'}
    validates :price, numericality: { message: 'Prices must be entered as numbers.'}, presence: true
    validates :item_sub_category_id, presence: {message: 'Items must belong to a sub-category.'}
    validates :item_category_id, presence: { message: 'Items must have a category.' }


    scope :featured, -> { where(featured: true) }

    def has_photos?
        photos.count > 0
    end

    def primary_photo 
        @primary_photo ||= photos.find_by_primary(true) || photos.first
    end

    def primary_photo_url(style = :medium)
        if primary_photo
            primary_photo.image.url(style) 
        else
            'no_image_available.jpg'
        end
    end

    def primary_photo_size(style = :medium)
        primary_photo.try(:image).try(:image_size, style)
    end

    def category
        item_sub_category.item_category
    end

    def attach_photo(file_path)
        return nil unless File.exists?(file_path)
        item_photo = photos.new
        image_file = File.open(file_path)
        item_photo.image = image_file 
        image_file.close
        item_photo.save
    end

    def related_items(number_of_records = 5)
        Item.where(item_category: item_category, item_sub_category_id: item_sub_category.id).where.not(id: id).order('featured desc, view_count desc').limit(number_of_records)
    end

    def has_related_items?
        related_items.count > 0 
    end

    def to_param
        "#{id} #{title}".parameterize
    end


end

app/controllers/inventory/account_controller.rb
class Inventory::AccountController < Inventory::InventoryController
    def show
        current_user.build_location unless current_user.location
    end
    def update_user 
        if current_user.update(user_params) 
            flash.now[:notice] = 'User information saved'
        end
        render 'show'
    end

    private

    def user_params
        params.require(:user).permit(
            :first_name, 
            :last_name, 
            :password,
            :password_confirmation,
            :email => [:address],
            :location => [:city, :state, :postal_code]
        )
    end
end

app/controllers/inventory/billing_controller.rb
class Inventory::BillingController < Inventory::InventoryController
    if Rails.env.production?
        force_ssl
    end    

    def view
        current_instance.reload_customer
    end

    def new_card
    end

    def create_card
        current_instance.customer.cards.create(card: params[:stripe_token])
        redirect_to inventory_billing_path
    end

    def make_primary 
        current_instance.customer.default_card = params[:card_token]
        current_instance.customer.save
        redirect_to inventory_billing_path
    end

    def delete_card
        if current_instance.customer.cards.count == 1 
            flash[:notice] = "You must add an additional card before removing the last one."
        else
            current_instance.customer.cards.retrieve(params[:card_token]).delete
        end
        redirect_to inventory_billing_path
    end

    def cancel_account
        current_instance.update(cancelled: true, cancellation_reason: params[:reason])
        current_instance.customer.subscriptions.first.try(:delete)
        redirect_to inventory_billing_path
    end

end

app/controllers/inventory/inventory_controller.rb
class Inventory::InventoryController < ApplicationController 
    layout 'inventory' 

    before_action :check_instance

    private
    def check_instance
        redirect_to homepage_signin_path unless current_instance && current_user
    end

    def current_instance 
        @current_instance ||= current_user.try(:instance)
    end
    helper_method :current_instance

    def current_user
        @current_user ||= User.find(session[:user_id]) if session[:user_id]
    end
    helper_method :current_user

end

app/controllers/inventory/item_categories_controller.rb
class Inventory::ItemCategoriesController < Inventory::InventoryController

    before_action :set_item_category, only: [:show, :edit, :update, :destroy]

    def index
        @q = current_instance.item_categories.order(:name).search(params[:q])
        @item_categories = @q.result.page(page).per(per)
    end

    def show

    end

    
    def new
        @item_category = current_instance.item_categories.new
    end

    def create 
       @item_category = current_instance.item_categories.new(item_category_params)
      if @item_category.save
         redirect_to [:inventory, @item_category]
      else 
         render 'new' 
      end
    end

    def edit
    end

    def update
        if @item_category.update(item_category_params)
            redirect_to [:inventory, @item_category]
        else
            render 'edit'
        end
    end
       

    def destroy 
        @item_category.destroy
        redirect_to inventory_item_categories_path
    end


    private

    def set_item_category 
        @item_category = current_instance.item_categories.find_by_id(params[:id])
    end

    def item_category_params 
        params.require(:item_category).permit(:name)
    end
    
    def page 
        params[:page] || 0
    end
    
    def per
        params[:per] || 10
    end

end

app/controllers/inventory/item_photos_controller.rb
class Inventory::ItemPhotosController < Inventory::InventoryController

    before_action :set_item
    before_action :set_item_photo, only: [:set_primary, :destroy]

    def new
        @item_photo = @item.photos.new
        render layout: 'modal'
    end

    def create
       return redirect_to [:inventory, @item] unless params[:item_photo]
       @item.photos.new(params.require(:item_photo).permit(:image)) 
       if @item.save
           redirect_to [:inventory, @item]
       end
    end

    def destroy
        @item_photo.destroy
        redirect_to [:inventory, @item]
    end

    def set_primary
        ItemPhoto.where(item: @item).update_all(primary: false)
        @item_photo.update(primary:true)
        redirect_to [:inventory, @item]
    end

    def set_item
        @item = current_instance.items.find(params[:item_id])
    end
    
    def set_item_photo
        @item_photo = @item.photos.find(params[:id])
    end

end

app/controllers/inventory/item_sub_categories_controller.rb
class Inventory::ItemSubCategoriesController < Inventory::InventoryController 
    respond_to :html, :json

    before_action :set_item_category 
    before_action :set_item_sub_category, :only => [:show, :destroy, :edit, :update]


    def index
        @item_sub_categories = @item_category.item_sub_categories
        respond_with(@item_sub_categories)
    end


    def show

    end

    def new
        @item_sub_category = ItemSubCategory.new
    end

    def create
        @item_sub_category = @item_category.item_sub_categories.new(sub_category_params)
        if @item_sub_category.save
            redirect_to [:inventory, @item_category, @item_sub_category]
        else
            render 'new'
        end
    end

    def edit

    end

    def update
        if @item_sub_category.update(sub_category_params)
            redirect_to [:inventory, @item_category, @item_sub_category]
        else
            render 'edit'
        end
    end

    def destroy
        @item_sub_category.destroy
        redirect_to [:inventory, @item_category]
    end


    private

    def set_item_category
        @item_category = current_instance.item_categories.find_by_id(params[:item_category_id])
    end

    def set_item_sub_category 
        return nil unless @item_category
        @item_sub_category = @item_category.item_sub_categories.find_by_id(params[:id])
    end

    def sub_category_params
        params.require(:item_sub_category).permit(:name)
    end

end

app/controllers/inventory/items_controller.rb
class Inventory::ItemsController < Inventory::InventoryController

    before_action :set_item, only: [:show, :edit, :update, :destroy, :new_photo, :create_photo, :delete_photo]


    def index
        @search = current_instance.items.order(:id => :desc).search(params[:q])
        @items = @search.result.page(page).per(per)
    end

    def new
        @item = current_instance.items.new
    end

    def create
        @item = current_instance.items.new(item_params)
        if @item.save
            redirect_to [:inventory, @item]
        else
            render 'new'
        end
    end

    def edit
    end

    def update
        if @item.update(item_params)
            redirect_to [:inventory, @item]
        else
            render 'edit'
        end
    end

    def destroy
        @item.destroy
        redirect_to inventory_items_path
    end

    private

    def set_item 
        @item = current_instance.items.find(params[:id])
    end

    def item_params 
        item_params  = params.require(:item).permit(:title, :identifier, :description, :item_sub_category_id, :price, :item_category_id, :featured)
        item_params[:properties] = item_properties
        item_params

    end

    def item_properties 
        properties_hash = {}
        if params[:properties]
            params[:properties].each do |property| 
                properties_hash[property['property_name'].strip] = property['property_value'].strip if property['property_name'].present? && property['property_value'].present?
            end
        end
        properties_hash
    end
    
    def page
        params[:page] || 0
    end

    def per
        params[:per] || 15
    end

end

app/controllers/inventory/landing_controller.rb
class Inventory::LandingController < Inventory::InventoryController
    layout 'landing_trigger'
    before_action :set_trigger

    def land
        return render params[:view] if params[:view]
        if @current_trigger
            return render @current_trigger.view_name
        end 
        redirect_to inventory_items_path
    end

    def dissmiss
        @current_trigger.destroy
        redirect_to inventory_landing_path
    end

    private 

    def set_trigger
        @current_trigger ||= (current_user.landing_triggers.presentable.first || current_instance.landing_triggers.presentable.first)
    end


end

app/controllers/inventory/settings_controller.rb
class Inventory::SettingsController < Inventory::InventoryController
    def application_settings
        @instance = current_instance
        @company = current_instance.company
    end

    def update_application_settings
        @instance = current_instance
        if @instance.update(instance_params)
            flash.now[:notice] = 'Information updated successfully.'
        end
        render 'application_settings'
    end


    def apperance_settings
    end

    def remove_logo 
        current_instance.apperance_setting.update(logo_image: nil)
        redirect_to inventory_apperance_settings_path
    end

    def update_apperance_settings
        if current_instance.apperance_setting.update(apperance_params)
            flash.now[:notice] = 'Settings updated.'
        else 
            flash.now[:notice] = "Settings could not be updated."
        end
        render 'apperance_settings'
    end


    private 

    def instance_params
        params.require(:instance).permit( 
            :instance_name,
            company_attributes: [
                :company_name, 
                phone_number_attributes: [:number],
                location_attributes: [:street_address, :city, :state, :postal_code]
        ]
        )
    end


    def apperance_params
        params.require(:apperance_setting).permit(:scheme_name, :theme_name, :logo_image, :full_size_logo)
    end

end

app/helpers/inventory/account_helper.rb
module Inventory::AccountHelper
end

app/helpers/inventory/billing_helper.rb
module Inventory::BillingHelper
end

app/helpers/inventory/inventory_helper.rb
module Inventory::InventoryHelper 
    def side_nav_link(title, url, opts={}) 
        active_class = nil
        if opts[:controller] 
            if opts[:controller].is_a? Array
                active_class = "active" if opts[:controller].include? params[:controller].classify
            end
            if opts[:controller].is_a? String
                active_class = "active" if opts[:controller] == params[:controller].classify
            end
        end
        content_tag :li, class: active_class do
            link_to title, url
        end
    end

    def boolean_label(value) 
        cls = "boolean-label"
        cls += " true" if value == true
        cls += " false" if value == false
        value_string = (value==true ? 'yes' : 'no')
        content_tag :div, value_string, class: cls
    end

end

app/helpers/inventory/item_categories_helper.rb
module Inventory::ItemCategoriesHelper

    
end

app/helpers/inventory/item_photos_helper.rb
module Inventory::ItemPhotosHelper
end

app/helpers/inventory/item_sub_categories_helper.rb
module Inventory::ItemSubCategoriesHelper
end

app/helpers/inventory/items_helper.rb
module Inventory::ItemsHelper


    def detail_item(label_text, value_text) 
        content_tag :div do
            concat content_tag :span, label_text, class: 'label'
            concat content_tag :span, value_text, class: 'value'
        end
    end

end

app/helpers/inventory/landing_helper.rb
module Inventory::LandingHelper
end

app/helpers/inventory/settings_helper.rb
module Inventory::SettingsHelper
end

app/views/inventory/items/_form.html.erb
<%= simple_form_for [:inventory, @item] do |f| %>
    <%= f.input :title %>
    <%= f.input :identifier, label: 'Identifier', hint: 'This value can be used to track the item. This could be a serial number, UPC, or other identifying number.' %>
    <%= f.input :description, input_html: {rows: 10} %>
    <%= f.input :price %>
    <div class="input">
        <label>Condition</label>
        <%= f.select :condition, options_for_select(item_conditions, @item.condition), {}, data: { width: 200 }  %>
    </div>
    <%= f.association :item_category, label: 'Category', input_html: { data: { width: 300 } } %>
    <div class="input">
        <%= f.label :item_sub_category, 'Subcategory' %>
        <%= f.hidden_field :item_sub_category_id %>
    </div>
    <div class="input">
        <%= f.label :featured %>
        <label class="label-switch">
            <%= check_box :item, :featured %>
            <div class="checkbox"></div>
        </label>
    </div>
    <h3>Item attributes</h3>
    <p>Item attributes allow you to add custom information to the item. These details will be displayed along with the title. They can be used to give quick information about the item, such as weight, size, brand, etc.</p>
    <div class="item-properties">
        <% if @item.properties %>
            <% @item.properties.each do |k,v| %>
                <div class="property">
                    <%= text_field_tag 'properties[][property_name]', k %>
                    <%= text_field_tag 'properties[][property_value]', v %>
                </div>
            <% end %>
            <% (10 - @item.properties.count).times do %>
                <div class="property">
                    <%= text_field_tag 'properties[][property_name]', nil, placeholder: 'Attribute name' %>
                    <%= text_field_tag 'properties[][property_value]', nil, placeholder: 'Attribute value' %>
                </div>
            <% end %>
        <% else %>
            <% (10).times do %>
                <div class="property">
                    <%= text_field_tag 'properties[][property_name]', nil, placeholder: 'Attribute name' %>
                    <%= text_field_tag 'properties[][property_value]', nil, placeholder: 'Attribute value' %>
                </div>
            <% end %>
        <% end %>
    </div>
    <div class="form-actions">
        <%= f.submit %>
        <%= link_to 'Cancel', :back, class: 'button' %>
    </div>
<% end %>

app/views/inventory/items/edit.html.erb
<%= render 'form' %>

app/views/inventory/items/index.html.erb
<div class="toolbar">
    <ul class="left">
        <li><%= link_to icon('search', 'Search'), '', data: { searchbox: true } %></li>
    </ul>
    <ul class="right">
        <li><%= link_to icon('plus', 'New Item'), new_inventory_item_path %></li>
    </ul>
</div>
<div class="search-box">
    <%= search_form_for [:inventory, @search] do |f| %>
        <div class="input">
            <%= f.label :identifier_cont, 'Identifier' %>
            <%= f.search_field :identifier_cont %>
        </div>
        <div class="input">
            <%= f.label :title_cont, 'title' %>
            <%= f.search_field :title_cont %>
        </div>
        <div class="input range">
            <%= f.label :price_lt, 'Price from' %>
            <%= f.search_field :price_gt %>
            <%= f.label :price_lt, 'to' %>
            <%= f.search_field :price_lt %>
        </div>
        <div class="input">
            <%= f.label :item_category_id_eq, 'Category' %>
            <%= f.select :item_category_id_eq, 
                options_from_collection_for_select(current_instance.item_categories, :id, :name, @search.item_category_id_eq),  
                {include_blank: true}, 
                data: { width: 200 } %>
        </div>
        <div class="form-actions">
            <%= f.submit %>
            <%= link_to 'Close', '', class: 'close' %>
        </div>
    <% end %>
</div>
<div class="item-list">
    <% @items.each do |item| %>
        <%= link_to inventory_item_path(item) do %>
            <span class="title"><%= item.identifier %></span>
            <span class="description"><%= item.title %></span>
            <span class="arrow"><%= icon('chevron-right') %></span>
            <span class="right"><%= number_to_currency item.price %></span>
        <% end %>
    <% end %>
</div>

<%= paginate @items %>

app/views/inventory/items/new.html.erb
<%= render 'form' %>

app/views/inventory/items/show.html.erb
<div class="toolbar">
    <ul class="left">
    <li><%= link_to icon('eye', 'View Item Page'), browser_item_url(@item, subdomain: current_instance.instance_name)  %></li>
    </ul>
    <ul class="right">
        <li><%= link_to icon('trash-o', 'Delete item'), inventory_item_path(@item), data: {confirm: 'Are you sure you want to permanently delete this item?', method: 'delete'} %></li>
        <li><%= link_to icon('edit', 'Edit Details'), edit_inventory_item_path(@item) %></li>
        <li><%= link_to icon('camera', 'Add Photo'), new_inventory_item_item_photo_path(@item), data: { modal: true }  %></li>
    </ul>
</div>
<h3>Item Details</h3>
<div class="detail-list">
    <%= detail_item 'Identifier', @item.identifier %>
    <%= detail_item 'Title', @item.title %>
    <%= detail_item 'Price', number_to_currency(@item.price) %>
    <%= detail_item 'Featured', boolean_label(@item.featured) %>
    <%= detail_item 'Category', link_to(@item.category, [:inventory, @item.category]) %>
    <%= detail_item 'Subcategory', link_to(@item.item_sub_category, [:inventory, @item.category, @item.item_sub_category]) %>
    <%= detail_item 'View count', @item.view_count %>
    <% if @item.last_viewed_at %>
        <%= detail_item 'Last viewed', "#{time_ago_in_words(@item.last_viewed_at)} ago" %>
    <% end %>
    <%= detail_item 'Added on', @item.created_at.to_s(:short) %>
</div>

<h3>Item Photos</h3>
<% if @item.photos.count > 0 %>
<div class="photo-list">
    <% @item.photos.order(:created_at => :desc).each do |photo| %>
        <div class="photo-wrapper">
            <%= image_tag photo.image.url(:thumb) %>
            <div class="toolbar">
                <ul class="left">
                    <li><%= link_to icon('trash-o'), inventory_item_item_photo_path(@item, photo), data: { method: 'delete', confirm: 'Are you sure you want to permenantly remove this photo?'} %></li>
                </ul>
                <ul class="right">
                    <% if @item.primary_photo  == photo %> 
                        <li><%= link_to icon('star'), set_primary_inventory_item_item_photo_path(@item, photo), class: 'primary' %></li>
                    <% else %>
                        <li><%= link_to icon('star'), set_primary_inventory_item_item_photo_path(@item, photo) %></li>
                    <% end %>
                </ul>
            </div>
        </div>
    <% end %>
</div>
<% else %>
    <div class="no-data">
        <p>This item has no photos attached to it.</p>
        <%= link_to 'Add Photo', new_inventory_item_item_photo_path(@item), data: {modal:true} %> 
    </div>
<% end %>