config/routes.rb
Rails.application.routes.draw do

    namespace :browser, path: '/', constraints: lambda {|request| request.subdomain.present? && request.subdomain != 'www'} do
        get '/' => 'item_browser#land', :as => :landing
        get '/search' => 'item_browser#search', :as => :search
        get '/item/:id' => 'item_browser#show_item', :as => :item
        get '/category/:id' => 'item_browser#browse_category', :as => :category
    end

    namespace :homepage, path: '/' do
        get '/' => 'landing#land', :as => :landing
        get 'signup' => 'signup#signup', :as => :signup
        post 'signup' => 'signup#do_signup'
        get 'billing' => 'signup#billing', :as => :billing
        post 'billing' => 'signup#do_billing'
        get 'signin' => 'signin#show', :as => :signin
        post 'signin' => 'signin#signin'
        get 'signout' => 'signin#signout', :as => :signout
        get 'reset' => 'signin#reset_form', :as => :reset_password_form
        post 'reset' => 'signin#send_reset_email'
        get 'reset_password/:token' => 'signin#reset_password', :as => :reset_password
        post'reset_password/:token' => 'signin#update_password'
    end

    namespace :inventory do 
        get '/account' => 'account#show', :as => :account
        patch '/account' => 'account#update_user'
        get '/' => 'landing#land', :as => :landing
        resources :items do 
            resources :item_photos do
                member do 
                    get 'primary' => 'item_photos#set_primary', :as => :set_primary
                end
            end
        end
        resources :item_categories do 
            resources :item_sub_categories
        end
        scope 'settings' do 
            get 'application' => 'settings#application_settings', :as => :application_settings
            post 'application' => 'settings#update_application_settings'
            get 'apperance' => 'settings#apperance_settings', :as => :apperance_settings
            patch 'apperance' => 'settings#update_apperance_settings'
            get 'remove_logo' => 'settings#remove_logo', :as => :remove_logo 

            scope :billing do 
                get '/' => 'billing#view', :as => :billing
                get 'add_card' => 'billing#new_card', :as => :new_card
                post 'add_card' => 'billing#create_card'
                get 'primary_card' => 'billing#make_primary', :as => :make_primary_card
                get 'delete_card' => 'billing#delete_card', :as => :delete_card
                get 'cancel' => 'billing#confirm_cancel_account', :as => :cancel_account
                post 'cancel' => 'billing#cancel_account'
            end
        end
    end

    namespace :help do 
        get '/' => 'articles#landing', :as => :landing
        get ':article' => 'articles#article', :as => :article
    end
end

app/controllers/help/articles_controller.rb
class Help::ArticlesController < Help::BaseController

    before_action :validate_article, only: [:article]

    def landing 
        redirect_to help_article_path('getting_started')
    end

    def article
        render params[:article]
    end

    private

    def validate_article
        return render 'not_found' unless valid_article?
    end

    def valid_article?
       %w{getting_started domain categories item_photos related featured payment_security}.include? params[:article]
    end

end

app/controllers/help/base_controller.rb
class Help::BaseController < ApplicationController 
    layout 'help'


    private 

    def logged_in?
        User.exists?(id: session[:user_id]) 
    end
    helper_method :logged_in?

    def current_instance
        return nil unless current_user
        @current_instance ||= current_user.instance
    end 
    helper_method :current_instance 

    def current_user 
        return nil unless logged_in?
        @current_user ||= User.find(session[:user_id])
    end
    helper_method :current_user
end

app/helpers/help/articles_helper.rb
module Help::ArticlesHelper

    def help_nav_link(title, article)
        content_tag :li, class: (params[:article] == article ? 'active' :nil) do 
            link_to title, help_article_path(article)
        end


    end

end

app/views/help/articles/categories.html.erb
<%= content_for :title, 'Understanding item categories' %>
<h1>What are item categories</h1>
<p><span class="inline-note">When you delete a category all subcategories are also removed. Any items that are assoicated with that category or subcategory are also removed.</span>The first thing you should do is setup some <em>Item Categories</em> and <em>Sub categories</em>. Item categoires serve three important functions. First, they are useful for organizing your items, giving users the ability to look at items within a specific category. Second, categories are used to build the navigation on your page. This allows users to quickly access categories. The category links in the navigation of your page are dynamically created based on the categories that have the most items inside them.</p>
<p>When your account is setup a few categories will be automatically generated for you. You are free to change or remove them if you would like. You can add additional categories from the <%= link_to_if logged_in?, 'categories section', inventory_item_categories_path %> in the <%= link_to_if logged_in?, 'control panel', inventory_landing_path %>.</p>
<h1>Subcategories</h1>
<p><span class="inline-note">When you delete a subcategory the parent category is not removed. However any items that are associated with that subcateogry will be removed.</span>Each category can have a number of subcategories related to it. Items must belong to one category and one subcategory. Sub categories allow users further filter items when browsing by category. Like categories, subcategories are also used for finding related items to display to your users when they view a item.</p>
<p>When your account is first setup a number of categories are automatically generated for you. Each of these categories also have several subcategories as well. You can add, edit, and remove subcategories by viewing a specific category in the <%= link_to_if logged_in?, 'category section', inventory_item_categories_path %> of the <%= link_to_if logged_in?, 'control panel', inventory_landing_path %>

app/views/help/articles/domain.html.erb
<% content_for :title, 'Using your hockd web address' %>
<h1>Your hockd web address</h1>
<p>
<% if logged_in? %>
    When you created your account you were issued a web address at hockd.com. Your current hockd web address is <%= link_to "http://#{current_instance.instance_name}.hockd.com" %>.
<% else %>
    When you create an account you will be issued a hockd web address. You can customize this address in the form of <strong>http://mycustomname.hockd.com</strong>.
<% end %>
Your page will always be available at this address. However, you can use this url in different ways.

<h1>Using your hockd page as your company's website</h1>
<p>Your hockd page makes a great company website. If you would like to simply have your customers directly access this page you can simply give out your hockd url to your customers. If you want to use a custom domain for your hockd page, see <em>Using a custom domain</em> below.

<h1>Using a custom domain</h1>
<p><span class="inline-note">Domain masking allows you to redirect from one domain to another without changing the address in the users browser. This will allow your hockd page to be viewed from the custom domain and still list http://mycompany.com in the address bar</span>You may find that you want to use a custom domain for your hockd page. This way your customers can visit it by going to <strong>http://www.mycompany.com</strong>. Instead of your customers visiting your page with <strong>http://mycompany.hockd.com</strong>. If this is the case you will need to register your desired domain and redirect (and optionally mask) it to your hockd address (<strong>http://mycompany.hockd.com</strong>). GoDaddy offers cheap and reliable domain hosting, as well as the ability to easily redirect and mask your domain. You can view an article on how to redirect a domain below:</p>
<%= link_to 'GoDaddy Domain Forwarding and Masking', 'http://support.godaddy.com/help/article/422/forwarding-or-masking-your-domain-name' %>

<h1>Linking your hockd catalog to your existing website</h1>
<p>If you already have a company webpage, but would like your customers to be able to browse your hockd catalog, you can simple put a link on your current website. This requires a slight modification to your existing website. You can simple place a new link on your pages that are directed to your hockd.com address.</p>

<h1>Using a custom subdomain in my existing webpage</h1>
<p>If your company currently has a webpage and a custom domain. You would like to put a link on your webpage to your hockd address and catalog. However, you would also like your catalog to be located at a subdomain of your company's webpage domain (something like http://catalog.mycompany.com). You can do this in the same manner as <em>Using a custom domain</em> above. This time however you need to generate a new subdomain in your website and redirect it to your hockd address. To do this you may need to contact the company you registered your domain through, in order to figure out their process for doing this. If your domain was registered with GoDaddy you can visit the link below to read an article on redirecting subdomains.</p>
<%= link_to 'GoDaddy Domain Forwarding and Masking', 'http://support.godaddy.com/help/article/422/forwarding-or-masking-your-domain-name' %><br/> To view the subdomain documentaiton scroll near the bottom of the page.

app/views/help/articles/featured.html.erb
<% content_for :title, 'Understanding featured items' %>
<h1>What are featured items</h1>
<p>When an item is marked as featured it will take priority when being displayed in various parts of the system. The first page customers see when they visit your site will be a general list of items. Featured items will always take precedence to display here. This gives items marked as featured maximum exposure. Featured items will also take priority when related items are chosen to be displayed, when viewing a specific item.</p>
<p>Featured items are great for items that are in particularly high demand, or items that are associated with a time of year. Such as jewelry as Feburary approaches. You may also want to tag particular good deals as featured, in order to increase thier exposure. This gives you the beneifit of alerting customers to certain items even when they arent specifically looking for them.</p>
<h1>Marking items as featured</h1>
<p>When editing or creating an item there is a <em>featured switch</em> available on the form. Toggling this switch on will mark the item as featured. The item will begin to take priority over other items on the front page immediately.</p>

app/views/help/articles/getting_started.html.erb
<% content_for :title, 'Getting started' %>
<% unless logged_in? %>
    <h1>Signing up</h1>
    <p>To get started the first thing you must do is sign up for an account. Signup is easy and takes about two minutes. Simply fiill out a few pieces of contact information about yourself and your company and your off. To signup visit the <%= link_to 'signup page', homepage_signup_path %>.
<% end %>
<h1>First Steps</h1>
<p>Before you dive right in, this guide will try to help you understand how to get the best use of <strong>hockd</strong>. This guide will give a quick overview of some of the things you can setup to give your customers the best expierience. If you need detailed information about anything mentioned in this guide you can find additional information in the help section to the left.<p>
<h1>Customize your categories</h1>
<p><span class="inline-note">When you create a category, you should also create subcategories for it. You can do this when viewing a category.</span>Before you add any items it is a good idea to go through and setup your categories. When your account is first created a number of categories are generated for you. These are common categories, but may not apply to your business. You can add, remove, and edit categories from the <%= link_to_if logged_in?,'categories manager', inventory_item_categories_path %> in your <%= link_to_if logged_in?, 'control panel', inventory_landing_path %>.</p>
<p>For more information on categories and subcategories visit the <%= link_to 'categories article', help_article_path('categories') %>
<h1>Customize your sites apperance</h1>
<p>To customize your sites apperance goto the <%= link_to_if logged_in?, 'apperance section', inventory_apperance_settings_path %> section of the <%= link_to_if logged_in?, 'control panel', inventory_landing_path %>. From there you can select a theme and color scheme for your site. Themes change the overall layout and operation of the site, where as the color scheme changes the overall color design of the site. Instead of trying to customize all the colors on the site, you can simply pick from a set of predesigned schemes. These colors are picked to work well together and allow the site to flow well.</p>
<p>
<span class="inline-note">Logo images can be uploaded in any image format. However, for best results we suggest using a jpeg or PNG image file. For inline logos a PNG image with a transperant background will give you the best result.</span>
You can also upload your own logo to further customize your page. You can uplaod two different styles of logos:
<ul>
    <li><strong>Inline logos</strong> - Inline logos are small logos that appear in the corner of your site. This will generally be a smaller logo and company name. It will appear inline with additional information such as your company's phone number and address.</li>
    <li><strong>Full logos</strong> - Full fized logos take up the entire width of your site. This will replace the content in the sites header such as phone number and address. For this reason it is important to upload a logo that is 1000 pixels in width. A logo larger than that will be automatically scaled down to fit in the layout. Images smaller than this may be stretched to fill the area, which could make them appear undesirable.</p>
</ul>
<p>You can also customize the url of your site or give your page a full domain name such as http://mycompany.com. For more information on domains visit the <%= link_to 'website address', help_article_path('domain') %> section.</p>
<h1>Adding items to your catalog</h1>
<p><span class="inline-note">We recommend using stock product images for the primary image attached to an item.</span>Items can be added from the <%= link_to_if logged_in?, 'items section', inventory_items_path %> of the <%= link_to_if logged_in?, 'control panel', inventory_landing_path %>. Adding a new item requires only filling out a few details for the item. Basic item inforamtion such as the items title, description, price, item condition, categories, and featured selection.</p>
<p>Additionally, it is recommended to attach a photo to your item. This will greatly improve the quality of the listing.</p> 
<p>To learn how to get the best results when adding items photos visit the <%= link_to 'item photos', help_article_path('item_photos') %> section.</p>
<h1>Getting your customers to your site</h1>
<p>There are two methods of using your site, which depends on your situation and existing web pages.</p>
<% if logged_in? %>
    <p>Your customers can currently access your page by visiting <strong>http://<%= current_instance.instance_name %>.hockd.com</strong>.</p>
<% else %>
    <p>You will be able to pick a custom address for your application such as <strong>http://mycompany.hockd.com</strong>.</p>
<% end %>
<p>If your business currently has a website. You can simply add a link from your existing page to your hockd address. This way when customers visit your existing page they will be able to browse your catalog.</p>
<p>If your company doesn not currently have a website. Your hockd page makes a great business page. You can simply use it as your companies full website. In that case you can either give out your hockd url to your customer, or you can point your own custom domain to your hockd page. To learn more about registring and pointing a custom domain to your hockd page visit the <%= link_to 'website address', help_article_path('domain') %> help article.</p>

app/views/help/articles/item_photos.html.erb
<% content_for :title, 'Attaching photos to items' %>
<h1>Uploading item photos</h1>
<p>
To upload a photo and attach it to an item you must have the photo stored somewhere on your computer. 
<ul>
    <li>In the <%= link_to_if logged_in?, 'control panel', inventory_landing_path %> goto the <%= link_to_if logged_in?, 'item editor', inventory_items_path %>.</li>
    <li>Select an item, to view its details and information</li>
    <li>When viewing an item a <strong>Add Photo</strong> button is available. Click <strong>Add Photo</strong>.</li>
    <li>You will be prompted to select a file to upload. Press <strong>browse</strong> to open the file selection dialog. From here navigate to and select the file you wish to attach.</li>
</ul>
</p>
<p>Once you upload an image it will be scaled to various sizes to be used in different parts of the page. This helps speed up your users browsing experience by sending smaller images when possible. The photo will appear in the bottom section of the item details page. From here you have two additional options for each image. You can click on the trashcan (<%= icon('trash-o') %>) to delete the photo and remove it from the item. You can also set a specific photo as primary using the star button (<%= icon('star') %>). The star will be highlighted for the current primary photo. To switch another photo as primary clicking the star button under that photo will change it.</p>

<h1>Using multiple photos</h1>
<p>You can upload and attach multple photos to a single item. This is useful for items where a single picture can not convey enough detail, or if you are using stock images for the primary photo and actual images for secondary photos. When multple photos are attached to to an item the primary photo is the photo that is used to list item. When a customer views the item itself the additional photos will be available to view as well.</p>
<h1>Using product images as primary photos</h1>
<p>To improve the apperance of the catalog you can use stock product photos as the primary photo and then upload additional <em>actual</em> photos of the item itself. This allows the catalog to display the professional quality product photos when browsing the catlalog and your customers can still view the photos of the real item from the item's page</p>
<p>Generally you can find such photos from the manufactures website, or through image search services such as <%= link_to 'Google Image Search', 'http://images.google.com' %>.

app/views/help/articles/landing.html.erb
<% content_for :title, 'Control Panel Help' %>
test

app/views/help/articles/not_found.html.erb
<h1>Oops...</h1>
<p>We couldnt find the article you are looking for. You can browse the various help articles in the menu on the left of the page. if you need additional help you can ask us a question below.</p>

app/views/help/articles/payment_security.html.erb
<% content_for :title, 'Payment security' %>
<h1>Billing details</h1>
<p>We take security very seriously and as a result have chosen to take every step possible to ensure maximum payment security for our customers.</p>
<p>Our system never interacts with your payment details. When you submit your credit card information it is transmitted through a secure connection directly from your web browser to our payment processing partners. This process completely bypasses our system. This means we do not store, or have access to, your actual billing details. This helps us make sure that your payment credentials are kept secure and safe.</p>
<p>When dealing with your account information we implement high level encryption across the site, in order to further protect any information we do collect.</p>
<p>If you have any additional questions or concerns about our payment system don't hesitate to ask us. You can simply type a question below and we will answer any questions, or address any concerns, you may have.</p>

app/views/help/articles/related.html.erb
<%= content_for :title, "Understanding related items" %> 
<h1>What are related items</h1>
<p>Related items are displayed to a user when they view an item in your catalog. We will automatically attempt to find similar items to the item they are viewing and display them below the they are looking at. This helps items get more exposure to customers that might be interested in them.</p>
<h1>How to use ralated items</h1>
<p>There is no setup or configuration needed for related items. They will automatically appear on item pages.</p>
<h1>How related items are chosen</h1>
<p>Related items will come be pull from items in the same category and subcategory. Further there are text matching algorithims that attempt to find items with similar words in their title. Items which are viewed more often are also given priortiy to be selected.</p>